# Base image
FROM nginx:latest

# Copy v2's index.html into the Nginx web server directory
COPY ./v2/index.html /usr/share/nginx/html/index.html

# Introduce a failing command to simulate a runtime failure
CMD ["nginix", "-wrong-command"]


# Expose the default Nginx port
EXPOSE 80
