name: Deploy MyApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t myapp:v2 .
          docker tag myapp:v2 ${{ secrets.DOCKER_USERNAME }}/myapp:v2

      - name: Push Docker image to registry
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:v2

      - name: Deploy new container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:v2
          docker run -d --name myapp_v2 -p 5001:5000 ${{ secrets.DOCKER_USERNAME }}/myapp:v2
          sed -i 's/myapp_v1/myapp_v2/' /etc/nginx/nginx.conf
          systemctl reload nginx
          sleep 10
          if curl -f http://localhost:5001/health; then
            docker stop myapp_v1 && docker rm myapp_v1
          else
            echo "Deployment failed, rolling back"
            docker stop myapp_v2 && docker rm myapp_v2
          fi
          EOF

      - name: Notify Slack on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"🚨 Deployment failed! Rolling back to previous version."}' ${{ secrets.SLACK_WEBHOOK_URL }}
