name: Deploy MyApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t myapp:v2 .

      - name: Tag and Push Docker Image
        run: |
          docker tag myapp:v2 my-docker-repo/myapp:v2
          docker push my-docker-repo/myapp:v2

      - name: Deploy Application
        run: |
          ssh user@your-server << 'EOF'
            set -e
            # Pull the latest version of the Docker image
            docker pull my-docker-repo/myapp:v2

            # Run the new Docker container (if it fails, rollback)
            docker run -d --name myapp-v2 -p 5001:5000 my-docker-repo/myapp:v2 || exit 1

            # Update Nginx configuration to reflect the new port
            sed -i 's/5000/5001/g' /etc/nginx/sites-available/default
            nginx -s reload

            # Check if the application is up, if not, rollback
            sleep 10
            curl -f http://localhost:5001 || (docker stop myapp-v2 && docker rm myapp-v2 && exit 1)

            # Stop and remove the old container
            docker stop myapp-v1 || true
            docker rm myapp-v1 || true

            # Rename new container to the old container's name
            docker rename myapp-v2 myapp-v1
          EOF
        continue-on-error: true

      - name: Rollback on Failure
        if: failure()
        run: |
          ssh user@your-server << 'EOF'
            # If the deployment failed, stop and remove the new container
            docker stop myapp-v2 || true
            docker rm myapp-v2 || true

            # Revert Nginx configuration to the previous port
            sed -i 's/5001/5000/g' /etc/nginx/sites-available/default
            nginx -s reload
          EOF

      - name: Notify Slack on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "Deployment failed! Keeping the previous version running."
          SLACK_COLOR: "danger"
