name: Deploy MyApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -lah

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t myapp:v2 -f Dockerfile-v2 .

      - name: Push Docker Image
        run: |
          docker tag myapp:v2 my-docker-repo/myapp:v2
          docker push my-docker-repo/myapp:v2

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
            set -e
            docker pull my-docker-repo/myapp:v2
            docker run -d --name myapp-v2 -p 5001:5000 my-docker-repo/myapp:v2 || exit 1
            sed -i 's/5000/5001/g' /etc/nginx/sites-available/default
            nginx -s reload
            sleep 10
            curl -f http://localhost:5001 || (docker stop myapp-v2 && docker rm myapp-v2 && exit 1)
            docker stop myapp-v1
            docker rm myapp-v1
            docker rename myapp-v2 myapp-v1
          EOF
        continue-on-error: true

      - name: Rollback on Failure
        if: failure()
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
            docker stop myapp-v2 || true
            docker rm myapp-v2 || true
            sed -i 's/5001/5000/g' /etc/nginx/sites-available/default
            nginx -s reload
          EOF

      - name: Notify Slack on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "Deployment failed! Keeping the previous version running."
          SLACK_COLOR: "danger"
