name: Docker Deployment with Rollback

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image (v2)
      run: |
        docker build -t my-app:v2 -f Dockerfile-v2 .
        docker tag my-app:v2 my-dockerhub-repo/my-app:v2

    - name: Push Docker Image to Registry
      run: docker push my-dockerhub-repo/my-app:v2

    - name: Deploy New Container
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'bash -s' < deploy_and_rollback.sh

    - name: Alert on Deployment Failure
      if: failure()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        slack-token: ${{ secrets.SLACK_TOKEN }}
        text: "🚨 Deployment of v2 failed. Rolled back to v1 successfully."
